### ISSUE TITLE
[BUG] [UI] After submitting to a round, I am still able to add projects to my cart from the project page 

### ISSUE THREAD

**Issue by renaobrien** [gitcoinco/MACI_QF#101]
**Describe the bug**
After submitting donations with my wallet address, I was able to go back to the round, and unable to see the 'add to cart button' HOWEVER I was able to add projects directly from their pages. I was unable to submit the donation, and have no console input once hitting submit at this time. 

**Additional context**
When I go hit the back browser button, the amount of ETH to contribute has changed (originally input 0.0001, changed to 0.0003) 

https://drive.google.com/file/d/1J6GZYwleeUyYkReiVO6XKnnO5ORY8KJ2/view?usp=sharing

**Comment by thelostone-mc** [comment]
fixed via https://github.com/gitcoinco/MACI_QF/pull/100
