### ISSUE TITLE
Setup gitcoin.co domains for MACI

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/MACI_QF#20]
Update DNS to add the MACI domains

- [x] Builder
- [x] Manager
- [x] Explorer

https://manager-maci.gitcoin.co/
https://builder-maci.gitcoin.co/
https://explorer-maci.gitcoin.co/

**Comment by 0xKurt** [comment]
How should the domain look like?


- [ ] `explorer.maci.gitcoin.co`
- [ ] `explorer-maci.gitcoin.co`
- [ ] `maci-explorer.gitcoin.co`
- [ ] `maci.explorer.gitcoin.co`

- [ ] `explorer.zuzalu.gitcoin.co`
- [ ] `explorer-zuzalu.gitcoin.co`
- [ ] `zuzalu-explorer.gitcoin.co`
- [ ] `zuzalu.explorer.gitcoin.co`

- [ ] `other`
