### ISSUE TITLE
Educate users about decimal issue on donation

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/MACI_QF#21]
If a user donates 0.1 ETH and, on his donation overview it will show something like 0.097 eth which is caused due to maci calculations

**Nick** Another solution is to just based on the voiceCredits that we are indeed make use to send this amount as a donation and inform the user about this inconsistency as a MACI related thing. 

- That way people cannot complain that they lost money
- If we inform them well why they donated 0.097 instead of 0.1
- We are going to display those values on the Cart before checking out

**Comment by 0xKurt** [comment]
closed in favor of #37
