### ISSUE TITLE
[BUG] Github and Twitter verification fails 

### ISSUE THREAD

**Issue by meglister** [gitcoinco/MACI_QF#92]
**Describe the bug**
I am not able to verify my twitter or github when applying to a MACI round

**To Reproduce**
- enter twitter username and click verify
- enter github username/org and click verify
- screen recording: https://www.loom.com/share/c672449d8e7340be96ca0331c072d81c

**Expected behavior**
- i would expect to get a confirmation that the verification has been successful. no errors observed

**Screenshots**
see screen recording above

**Logs**
nothing in the console

**Possible Solution**
??

**Additional context**
n/a

**Comment by 0xKurt** [comment]
We need access to twitter.
Need to talk to andrea or passport to figure out why github is not working

**Comment by thelostone-mc** [comment]
had to work with passport team to support MACI.
Github verification works.
Twitter verification is disabled as it's not a requirement for MACI
