### ISSUE TITLE
[BUG] Users should be able to add to cart prior to connecting their wallet

### ISSUE THREAD

**Issue by meglister** [gitcoinco/MACI_QF#93]
**Describe the bug**
There is no add to cart button on the round homepage (eg - https://explorer-maci.gitcoin.co/#/round/11155111/346) or on the project page (https://explorer-maci.gitcoin.co/#/round/11155111/346/0xb543d56ee04f516602057429ec4f1c85c19b1319) before the user has connected their wallet. 

**To Reproduce**
Load links above

**Expected behavior**
Add to cart button should be present in both places. A user should only be blocked on submitting a donation prior to connecting their wallet

**Screenshots**
n/a 

**Logs**
n/a

**Possible Solution**
Add to cart should be supported

**Additional context**
n/a

**Comment by thelostone-mc** [comment]
So the caveat here is that we would need to know the wallet address to know if the person has already voted.
Because if they've already voted -> we cannot allow them to add to cart and re-vote
This is expected behaviour. Will bring it up on standup to discuss other options

**Comment by nijoe1** [comment]
> So the caveat here is that we would need to know the wallet address to know if the person has already voted. Because if they've already voted -> we cannot allow them to add to cart and re-vote This is expected behaviour. Will bring it up on standup to discuss other options

We can still show the add to cart but make it not clickable and include a tooltip on the btn "connect wallet" or when already contributed "you cannot contribute twice"

**Comment by thelostone-mc** [comment]
Synced internally with team. Agreed that this is expected behaviour and not making any changes as of now
