### ISSUE TITLE
[Not really a BUG] -- Make the contribution amounts & joining allowlist more straightforward

### ISSUE THREAD

**Issue by meglister** [gitcoinco/MACI_QF#95]
**Describe the bug**
As a new user, James didn't realize how to get voice credits -- and I observed as a new user that joining the allowlist was not straightforward. Can we add some design to the cart page to make the decision making process (as follows) more obvious/straightforward?
1- connect zupass (or realized you don't have one/cant)
2- understand donation limits, set your donation amount
3- finally, allocate VCs

Right now, I think we've tackled #3, but the setup for 1/2 still needs some work!

**Additional context**
happy to chat thru this

**Comment by bhargavaparoksham** [comment]
fixed as part of https://github.com/gitcoinco/MACI_QF/pull/109
