### ISSUE TITLE
Browser doesn't find metamask without refresh

### ISSUE THREAD

**Issue by positonic** [gitcoinco/MACI_QF#97]
**Describe the bug**
When I land on explorer and builder I have to refresh or it doesn't find my metamask...

**To Reproduce**
Go to https://explorer-maci.gitcoin.co/ and click connect wallet and select metamask.

**Expected behavior**
Metamask should open for connection

**Screenshots**
<img width="1541" alt="image" src="https://github.com/gitcoinco/MACI_QF/assets/10499048/ba40e6c2-1b00-4b7b-a8d4-d05cbd5e1208">
Screenshot with logs:
<img width="1713" alt="image" src="https://github.com/gitcoinco/MACI_QF/assets/10499048/6f729b55-2bc5-4997-baeb-e89ff648260d">

**Logs**
See above

**Possible Solution**
No idea. Could be some sort of synch loading issue

**Comment by thelostone-mc** [comment]
Just tested it out on chrome and safari and firefox and it seems to work.
Also tried it on incognito and scanned from mobile metamask app and it works
