### ISSUE TITLE
Must specify contribution before adding voice credits message (Usability suggestion)

### ISSUE THREAD

**Issue by positonic** [gitcoinco/MACI_QF#98]
**Describe the bug**
<img width="1587" alt="image" src="https://github.com/gitcoinco/MACI_QF/assets/10499048/f56f45e4-b799-4fa5-8878-898db668749f">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, add logs or stack traces to help us debug the issue.

**Possible Solution**
If you have an idea of what might be causing the issue or a suggestion for a fix, please let us know.

**Additional context**

**Comment by bhargavaparoksham** [comment]
fixed as part of https://github.com/gitcoinco/MACI_QF/pull/109
